# Generated by Django 3.1.7 on 2021-03-17 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lista_spese', '0003_auto_20210317_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesa',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
